version: '3.4'

services:
  backend:
    image: backend
    depends_on:
      - postgres
    restart: always
    ports:
      - 5000:80

  postgres:
    container_name: postgres
    image: postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jo31fMLj0YfC1xa
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend

  proxy:
    image: nginx:mainline
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"  

    
volumes:
 pgdata: